name: home_-_option_1
timestamp: 1550866354
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1544807178
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-7972: 'System Messages'
  logo:
    logo-9608: 'Logo / Image'
    logo-1407: 'Logo / Image'
  menu:
    menu-6409: Menu
  social:
    social-3171: Social
  owlcarousel:
    owlcarousel-9030: 'Owl Carousel'
  position:
    position-position-4734: Aside
    position-position-3949: Sidebar
  content:
    system-content-1587: 'Page Content'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
  custom:
    custom-4803: 'Custom HTML'
  horizontalmenu:
    horizontalmenu-8740: 'Horizontal Menu'
  totop:
    totop-8692: 'To Top'
  copyright:
    copyright-7309: Copyright
inherit:
  default:
    footer: footer
    logo-1407: logo-9571
    custom-4803: custom-5023
    horizontalmenu-8740: horizontalmenu-9034
    totop-8692: totop-8670
    copyright-7309: copyright-1736
