name: home_-_option_1
timestamp: 1551303563
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1544807178
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  header: Header
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  abovefoot: Abovefoot
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9221: 'Logo / Image'
    logo-9455: 'Logo / Image'
    logo-1407: 'Logo / Image'
  messages:
    system-messages-7972: 'System Messages'
  menu:
    menu-6409: Menu
  owlcarousel:
    owlcarousel-9030: 'Owl Carousel'
  position:
    position-position-4734: Aside
    position-position-3949: Sidebar
  content:
    system-content-1587: 'Page Content'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
  horizontalmenu:
    horizontalmenu-5171: 'Explore Menu'
    horizontalmenu-3704: Aquire
  totop:
    totop-8692: 'To Top'
  copyright:
    copyright-7309: Copyright
inherit:
  default:
    abovefoot: abovefoot
    footer: footer
    logo-9455: logo-4773
    horizontalmenu-5171: horizontalmenu-9034
    horizontalmenu-3704: horizontalmenu-6755
    totop-8692: totop-8670
    copyright-7309: copyright-1736
    logo-1407: logo-9571
