version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1544807178
layout:
  /header/:
    -
      - logo-9221
  /navigation/:
    -
      - system-messages-7972
    -
      - menu-6409
  /intro/:
    -
      - owlcarousel-9030
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'aside 25':
          -
            - position-position-4734
      -
        'mainbar 50':
          -
            - system-content-1587
      -
        'sidebar 25':
          -
            - position-position-3949
  abovefoot: {  }
  footer: {  }
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  header:
    attributes:
      boxed: ''
      class: center
      variations: 'nopaddingall nomarginall'
  navigation:
    type: section
    attributes:
      boxed: ''
      class: 'nopaddingall center'
      variations: nomarginall
  intro:
    type: section
    attributes:
      boxed: '2'
      class: ''
      variations: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  abovefoot:
    type: section
    inherit:
      outline: default
      include:
        - children
        - attributes
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9221:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://header/marquee_willson_red-1.jpg'
      svg: ''
      class: ''
  owlcarousel-9030:
    title: 'Owl Carousel'
    attributes:
      autoplay: enable
      imageOverlay: disable
      items:
        -
          class: ''
          image: 'gantry-media://2019/02/musicman_bnr1.jpg'
          title: ''
          desc: ''
          link: /biography
          linktext: ''
          buttonclass: button-outline
          disable: '0'
          name: 'Meredith Marching'
        -
          class: ''
          image: 'gantry-media://2019/02/musicman_bnr2.jpg'
          title: ''
          desc: ''
          link: /musicals
          linktext: Musicals
          buttonclass: button-outline
          disable: '0'
          name: 'The Music Man'
        -
          class: ''
          image: 'gantry-media://2019/02/musicman_bnr3.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          disable: '0'
          name: Bio1
        -
          class: ''
          image: 'gantry-media://2019/02/musicman_bnr4.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          disable: '0'
          name: 'MusicMan Square'
        -
          class: ''
          image: 'gantry-media://2019/02/musicman_bnr5.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          disable: '0'
          name: 'Bio 2'
    block:
      class: centered
  position-position-4734:
    title: Aside
    attributes:
      key: aside
  position-position-3949:
    title: Sidebar
    attributes:
      key: sidebar
