name: _error
timestamp: 1549662600
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1549662593
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-2001: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-1051: Menu
  messages:
    system-messages-9967: 'System Messages'
  content:
    system-content-2795: 'Page Content'
  copyright:
    copyright-6077: Copyright
  spacer:
    spacer-2364: Spacer
  branding:
    branding-7125: Branding
  mobile-menu:
    mobile-menu-8374: Mobile-menu
inherit: {  }
