version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1549662593
layout:
  /header/:
    -
      - 'logo-2001 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-1051
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-9967
    -
      - system-content-2795
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6077 40'
      - 'spacer-2364 30'
      - 'branding-7125 30'
  offcanvas:
    -
      - mobile-menu-8374
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
