name: _body_only
timestamp: 1549662600
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1549662593
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9033: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-4264: Menu
  messages:
    system-messages-6451: 'System Messages'
  content:
    system-content-3673: 'Page Content'
  copyright:
    copyright-1777: Copyright
  spacer:
    spacer-4139: Spacer
  branding:
    branding-1324: Branding
  mobile-menu:
    mobile-menu-3300: Mobile-menu
inherit: {  }
