version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1549662593
layout:
  /header/:
    -
      - 'logo-9033 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-4264
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-6451
    -
      - system-content-3673
  /footer/:
    -
      - position-footer
    -
      - 'copyright-1777 40'
      - 'spacer-4139 30'
      - 'branding-1324 30'
  offcanvas:
    -
      - mobile-menu-3300
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
