version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1544807178
layout:
  /header/:
    -
      - logo-8934
  /navigation/:
    -
      - system-messages-7972
    -
      - 'logo-9608 20'
      - 'menu-6409 80'
  /intro/:
    -
      - owlcarousel-9377
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'aside 25':
          -
            - position-position-4734
      -
        'mainbar 50':
          -
            - system-content-1587
      -
        'sidebar 25':
          -
            - position-position-3949
  /footer/:
    -
      - 'logo-9571 10'
      - 'copyright-1736 30'
      - 'horizontalmenu-9034 45'
      - 'totop-8670 15'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  header:
    attributes:
      boxed: '0'
      class: ''
      variations: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  intro:
    type: section
    attributes:
      boxed: '0'
      class: ''
      variations: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: '0'
      class: ''
      extra: {  }
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-8934:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://marquee_willson_red.jpg'
      link: '1'
      svg: ''
  logo-9608:
    title: 'Logo / Image'
  owlcarousel-9377:
    title: 'Owl Carousel'
    attributes:
      items:
        -
          class: slide
          image: 'gantry-media://MWilson-marching.jpg'
          title: Title
          desc: 'Description is what this is'
          link: /bio
          linktext: 'MORE:::::::::::'
          buttonclass: button-outline
          disable: '0'
          name: march
        -
          class: slide
          image: 'gantry-media://2019/02/image-18.png'
          title: Title
          desc: 'Description is what this is'
          link: /bio
          linktext: 'MORE:::::::::::'
          buttonclass: button-outline
          disable: '0'
          name: march
  position-position-4734:
    title: Aside
    attributes:
      key: aside
  position-position-3949:
    title: Sidebar
    attributes:
      key: sidebar
  logo-9571:
    title: 'Logo / Image'
  horizontalmenu-9034:
    title: 'Horizontal Menu'
    attributes:
      items:
        -
          text: Gantry
          link: 'http://gantry.org'
          name: Gantry
        -
          text: Documentation
          link: 'http://docs.gantry.org'
          name: Documentation
        -
          text: Download
          link: 'http://gantry.org/downloads'
          name: Download
  totop-8670:
    title: 'To Top'
