name: musicals
timestamp: 1552061969
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1544807178
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  content:
    system-content-1587: 'Page Content'
  contentarray:
    contentarray-3069: 'WordPress Posts'
  messages:
    system-messages-6323: 'System Messages'
  logo:
    logo-7591: 'Logo / Image'
    logo-3317: 'Logo / Image'
  menu:
    menu-4240: Menu
  custom:
    custom-6314: 'Custom HTML'
  position:
    position-position-3746: Aside
    position-position-5393: Sidebar
  copyright:
    copyright-8137: Copyright
  mobile-menu:
    mobile-menu-3363: Mobile-menu
inherit:
  default:
    navigation: navigation
    header: header
    intro: intro
    features: features
    utility: utility
    testimonials: testimonials
    expanded: expanded
    aside: aside
    sidebar: sidebar
    footer: footer
    offcanvas: offcanvas
    system-messages-6323: system-messages-7972
    logo-7591: logo-9608
    menu-4240: menu-6409
    custom-6314: custom-4706
    position-position-3746: position-position-4734
    position-position-5393: position-position-3949
    copyright-8137: copyright-1736
    logo-3317: logo-9571
    mobile-menu-3363: mobile-menu-5697
